set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 6 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 7 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 8 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 9 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 10 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 11 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 12 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 13 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 14 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 15 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 16 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 17 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 18 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 19 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 20 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 21 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 22 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 61 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 13 and name OND"]
set sel2 [atomselect top "resid 110 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 13 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 16 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 17 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 19 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 20 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 24 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 25 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 26 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 27 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 28 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 29 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 30 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 31 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 32 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 33 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 34 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 35 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 36 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 38 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 107 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 108 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 109 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 30 and name OND"]
set sel2 [atomselect top "resid 110 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 26 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 29 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 30 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 32 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 33 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 34 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 35 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 36 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 37 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 38 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 40 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 41 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 42 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 38 and name OND"]
set sel2 [atomselect top "resid 104 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 25 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 42 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 43 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 45 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 46 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 47 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 48 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 49 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 50 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 51 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 52 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 53 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 54 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 55 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 56 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 57 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 49 and name OND"]
set sel2 [atomselect top "resid 58 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 28 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 78 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 79 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 80 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 81 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 82 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 83 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 84 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 85 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 86 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 87 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 88 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 89 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 92 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 93 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 94 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 96 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 133 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 135 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 136 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 82 and name OND"]
set sel2 [atomselect top "resid 137 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 99 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 100 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 101 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 102 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 103 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 104 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 105 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 106 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 107 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 108 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 109 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 110 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 111 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 112 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 113 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 114 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 106 and name OND"]
set sel2 [atomselect top "resid 115 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 109 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 110 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 111 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 112 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 113 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 114 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 115 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 116 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 117 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 113 and name OND"]
set sel2 [atomselect top "resid 118 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 119 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 120 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 121 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 122 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 123 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 124 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 125 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 126 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 127 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 128 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 139 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 140 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 141 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 123 and name OND"]
set sel2 [atomselect top "resid 142 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 124 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 125 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 126 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 127 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 133 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 134 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 135 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 136 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 137 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 138 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 139 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 140 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 141 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
set sel1 [atomselect top "resid 139 and name OND"]
set sel2 [atomselect top "resid 142 and name N"]
label add Bonds 0/[$sel1 list] 0/[$sel2 list]
